server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/umbrella?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

mqtt.broker=tcp://broker.hivemq.com:1883
mqtt.client-id=umbbk-9f3a
mqtt.topic-event=device/001/event